package com.busticket.busticketbooking.dto.ReportDTO;

import jakarta.validation.constraints.Digits;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;

// DTO used to send revenue report data for agencies
public class RevenueByAgencyResponseDTO {

    // Stores unique agency ID
    @NotNull(message = "Agency id is required")
    private Integer agencyId;

    // Stores travel agency name
    @NotBlank(message = "Agency name is required")

    // Limits agency name length to 255 characters
    @Size(max = 255, message = "Agency name must not exceed 255 characters")
    private String agencyName;

    // Stores total revenue generated by agency
    @NotNull(message = "Total revenue is required")

    // Ensures revenue amount is greater than 0
    @Positive(message = "Amount must be greater than 0")

    // Restricts decimal format for revenue value
    @Digits(integer = 8, fraction = 2,
            message = "Amount must have up to 8 integer digits and 2 decimal places")
    private BigDecimal totalRevenue;

    // Stores total booking count of agency
    @NotNull(message = "Total bookings is required")
    private Long totalBookings;

    // Default constructor
    public RevenueByAgencyResponseDTO() {
    }

    // Parameterized constructor for object initialization
    public RevenueByAgencyResponseDTO(Integer agencyId,
                                      String agencyName,
                                      BigDecimal totalRevenue,
                                      Long totalBookings) {
        this.agencyId = agencyId;
        this.agencyName = agencyName;
        this.totalRevenue = totalRevenue;
        this.totalBookings = totalBookings;
    }

    // Returns agency ID
    public Integer getAgencyId() {
        return agencyId;
    }

    // Sets agency ID
    public void setAgencyId(Integer agencyId) {
        this.agencyId = agencyId;
    }

    // Returns agency name
    public String getAgencyName() {
        return agencyName;
    }

    // Sets agency name
    public void setAgencyName(String agencyName) {
        this.agencyName = agencyName;
    }

    // Returns total revenue
    public BigDecimal getTotalRevenue() {
        return totalRevenue;
    }

    // Sets total revenue
    public void setTotalRevenue(BigDecimal totalRevenue) {
        this.totalRevenue = totalRevenue;
    }

    // Returns total booking count
    public Long getTotalBookings() {
        return totalBookings;
    }

    // Sets total booking count
    public void setTotalBookings(Long totalBookings) {
        this.totalBookings = totalBookings;
    }
}