package com.busticket.busticketbooking.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

/*
 * @Entity tells Hibernate that this class
 * should be mapped as a database entity.
 */
@Entity

/*
 * @Table specifies database table name.
 * Here table name is "drivers".
 */
@Table(name = "drivers")
public class Driver {

    /*
     * @Id marks this field as Primary Key.
     *
     * @GeneratedValue(strategy = GenerationType.IDENTITY)
     * means ID value will be auto-generated by MySQL.
     *
     * @Column specifies database column name.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "driver_id")
    private Integer id;

    /*
     * Stores driver's license number.
     *
     * @NotBlank ensures field cannot be null or empty.
     *
     * @Size restricts maximum length.
     *
     * @Pattern validates license number format.
     */
    @NotBlank(message = "License number is required")
    @Size(max = 20, message = "License number must not exceed 20 characters")
    @Pattern(
            regexp = "^[A-Za-z0-9\\- ]{3,20}$",
            message = "License number format is invalid"
    )
    @Column(name = "license_number", nullable = false, length = 20)
    private String licenseNumber;

    /*
     * Stores driver name.
     *
     * Validation ensures proper input.
     */
    @NotBlank(message = "Driver name is required")
    @Size(max = 255, message = "Driver name must not exceed 255 characters")
    @Column(nullable = false, length = 255)
    private String name;

    /*
     * Stores driver's phone number.
     *
     * @Pattern ensures only digits are allowed
     * and number length should be between 10 to 15.
     */
    @NotBlank(message = "Phone number is required")
    @Pattern(
            regexp = "^[0-9]{10,15}$",
            message = "Phone number must contain 10 to 15 digits"
    )
    @Size(max = 15, message = "Phone number must not exceed 15 characters")
    @Column(nullable = false, length = 15)
    private String phone;

    /*
     * Many drivers can belong to one office.
     *
     * @ManyToOne defines relationship:
     * Many Drivers -> One AgencyOffice
     *
     * @JoinColumn creates foreign key "office_id".
     */
    @ManyToOne
    @JoinColumn(name = "office_id")
    private AgencyOffice office;

    /*
     * Many drivers can have same address.
     *
     * @ManyToOne relationship:
     * Many Drivers -> One Address
     *
     * @JoinColumn creates foreign key "address_id".
     */
    @ManyToOne
    @JoinColumn(name = "address_id")
    private Address address;

    /*
     * Default constructor required by Hibernate/JPA.
     */
    public Driver() {
    }

    /*
     * Parameterized constructor used to initialize object with values.
     */
    public Driver(Integer id,
                  String licenseNumber,
                  String name,
                  String phone,
                  AgencyOffice office,
                  Address address) {

        this.id = id;
        this.licenseNumber = licenseNumber;
        this.name = name;
        this.phone = phone;
        this.office = office;
        this.address = address;
    }

    /*
     * Returns driver ID.
     */
    public Integer getId() {
        return id;
    }

    /*
     * Sets driver ID.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /*
     * Returns license number.
     */
    public String getLicenseNumber() {
        return licenseNumber;
    }

    /*
     * Sets license number.
     */
    public void setLicenseNumber(String licenseNumber) {
        this.licenseNumber = licenseNumber;
    }

    /*
     * Returns driver name.
     */
    public String getName() {
        return name;
    }

    /*
     * Sets driver name.
     */
    public void setName(String name) {
        this.name = name;
    }

    /*
     * Returns driver phone number.
     */
    public String getPhone() {
        return phone;
    }

    /*
     * Sets driver phone number.
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /*
     * Returns associated office object.
     */
    public AgencyOffice getOffice() {
        return office;
    }

    /*
     * Sets office object.
     */
    public void setOffice(AgencyOffice office) {
        this.office = office;
    }

    /*
     * Returns address object.
     */
    public Address getAddress() {
        return address;
    }

    /*
     * Sets address object.
     */
    public void setAddress(Address address) {
        this.address = address;
    }

    /*
     * equals() method compares two Driver objects.
     *
     * Two Driver objects are equal if their IDs are equal.
     */
    @Override
    public boolean equals(Object o) {

        // Checks if both references point to same object
        if (this == o) return true;

        // Checks if object is null or class differs
        if (o == null || getClass() != o.getClass()) return false;

        // Type casting Object into Driver
        Driver driver = (Driver) o;

        // Compare IDs
        return id != null && id.equals(driver.id);
    }

    /*
     * hashCode() is used internally in collections
     * like HashMap and HashSet.
     */
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }

    /*
     * toString() converts object data into readable string format.
     *
     * Useful for debugging and logging.
     */
    @Override
    public String toString() {

        return "Driver{" +
                "id=" + id +
                ", licenseNumber='" + licenseNumber + '\'' +
                ", name='" + name + '\'' +
                ", phone='" + phone + '\'' +
                ", officeId=" + (office != null ? office.getId() : null) +
                ", addressId=" + (address != null ? address.getId() : null) +
                '}';
    }
}